### ISSUE TITLE
storage import troubleshooting

### ISSUE THREAD

**Issue by kilianso** [sanketkheni01/fire-import#5]
hey there. cool repo!

I'm running into an issue using `fire-import storage`.  When using that command, a huge object is logged in the terminal and the last part of it says:

```
}
    data: 'Not Found'
},
isAxiosError: true
```

I'm logged in and authenticated and importing the firestore is working as expected, but not the storage. 
Any idea what am i missing? Any path that needs to be set somewhere? Oh and yes there is data. There are tons of images on the storage in a folder called `uploads`.

Would be cool to get a tip. Keep it up ✌️

**Comment by sanketkheni01** [comment]
Ok will look into it. This lib. definety needs some rework. I created this lib. back when I was a begginer.😅
Make sure to let me know how this library is useful to you? (It can help me decide to work on this project.) and which features you think should I add?

**Comment by kilianso** [comment]
Hey @sanketkheni01 

Ah okay i see. Well yes, it is useful since the workflow seems slightly easier than the official one provided by Firebase. I don't think more features are needed. I'll let you know if i can fix the storage import. Seems to be an issue with the path.

**Comment by sanketkheni01** [comment]
@kilianso okay thanks for letting me know, btw there is already one PR open. Check that one and let me know if it works. I didn't have much time to check that PR. Your issue might be related to that one.

Btw which OS are you using?

**Comment by kilianso** [comment]
Hey @sanketkheni01
Sorry about the delayed answer. Yes, storage import is fixed with version `1.1.11`. 🙌
Thanks!
